### ISSUE TITLE
怎么退出？

### ISSUE THREAD

**Issue by ywandy** [laike9m/PyPunchP2P#4]

**Comment by laike9m** [comment]
Ctrl+C 不行吗？

**Comment by ywandy** [comment]
Ctrl+c 屏幕有回显，不能退出 在2017年04月04日 01:55 ，Yao Zuo写道： Ctrl+C 不行吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by laike9m** [comment]
Ctrl + D 试试。我也忘记以前是怎么做的了……

**Comment by ywandy** [comment]
ctrl+D 和+c都不行

**Comment by laike9m** [comment]
Fixed.
