### ISSUE TITLE
为何 一边是对称 一边是完全锥形 却使用了服务器转发

### ISSUE THREAD

**Issue by leng-yue** [laike9m/PyPunchP2P#7]
![image](https://user-images.githubusercontent.com/25119060/27587905-cc8b584c-5b78-11e7-81c2-b8cd0558f284.png)

**Comment by laike9m** [comment]
额，只要有一边是 symmetric 就是走转发啊
https://github.com/laike9m/PyPunchP2P/blob/master/client.py#L163-L165

**Comment by leng-yue** [comment]
但是实际上端口限制 和一边是完全锥形都转发了。。

**Comment by leng-yue** [comment]
一边ip限制 一边完全锥形 原本不必转发吧

**Comment by laike9m** [comment]
我不知道实际情况怎样，但从 log 里看另一边不是 symmetric 么？意思是检测类型的时候出错了？


--
laike9m.com
