### ISSUE TITLE
测试有问题还请帮解答？

### ISSUE THREAD

**Issue by jiawenf** [laike9m/PyPunchP2P#8]
问题1：
一台独立外网ip的服务器，启动server.py 5678
    测试机A：RestrictNAT
    测试机B：SymmetricNAT 
    测试机C：RestrictNAT
    *测试机A和测试B可以连通，走的是转发模式
    *测试A和测试机C 一直在 UDP punching package 0 sent 循环中，无法打通
问题2：
    问题代码1：def start_working_threads(send, recv, event=None, *args, **kwargs) 参数报错， 把event=None 改成events=None
    问题代码1：ts = Thread(target=send, args=args, kwargs=kwarg) 参数报错，把删除参数 kwargs

**Comment by jiawenf** [comment]
测试问题

**Comment by laike9m** [comment]
没问题我就close了
